version: '3.1'

services:
  crud_server:
    build: ./crud_server_app
    ports:
      - 8765:8765
    depends_on:
      - database
    volumes:
      - ./crud_server_app:/app

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 12131415
      POSTGRES_USER: pm_user
      POSTGRES_DB: pm_db
      PGDATA: /var/lib/postgresql/data/pgdata
#    ports:
#      - 5432:5432

    volumes:
            - ./postgres_app/:/docker-entrypoint-initdb.d/

